global:
    scrape_interval:     15s
    evaluation_interval: 15s
scrape_configs:
    - job_name: 'faculdade'
      metrics_path: '/actuator/prometheus'
      scrape_interval: 5s
      static_configs:
        - targets: ["MacBook-Pro-de-Edson.local:9084", "MacBook-Pro-de-Edson.local:9083"